<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="9" total="10" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9581" started-at="2019-01-23T07:48:12Z" finished-at="2019-01-23T07:48:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="9581" started-at="2019-01-23T07:48:12Z" finished-at="2019-01-23T07:48:21Z">
      <class name="HelloSelenium">
        <test-method status="PASS" signature="setUp()[pri:0, instance:HelloSelenium@3712b94]" name="setUp" is-config="true" duration-ms="7931" started-at="2019-01-23T07:48:12Z" finished-at="2019-01-23T07:48:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="TC_010()[pri:0, instance:HelloSelenium@3712b94]" name="TC_010" duration-ms="698" started-at="2019-01-23T07:48:20Z" finished-at="2019-01-23T07:48:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[ERROR - Element is not visible] expected [true] but found [false],
[ERROR - Element is not visible] expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[ERROR - Element is not visible] expected [true] but found [false],
[ERROR - Element is not visible] expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at HelloSelenium.TC_010(HelloSelenium.java:150)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_010 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:HelloSelenium@3712b94]" name="tearDown" is-config="true" duration-ms="891" started-at="2019-01-23T07:48:20Z" finished-at="2019-01-23T07:48:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- HelloSelenium -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
